version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kleproject-api
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - kleproject-api-network
    environment:
      - LC_ALL=tr_TR.UTF-8
      - LANG=tr_TR.UTF-8
    hostname: kleproject-api

  db:
    image: mysql:8.0
    container_name: kleproject-api-db  
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: kleproject-api-db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: root
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - kleproject-api-network

networks:
  kleproject-api-network:

volumes:
  mysql-data:    
