version: '3'

services:
  frontend:
    image: 'frontendapp:latest'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" 
    volumes:
      - .:/var/www
    networks:
      - kleproject-api-network
  


networks:
  kleproject-api-network:
    external: true
